### ISSUE TITLE
Support additionalRemittanceInformation

### ISSUE THREAD

**Issue by judgej** [ardohr-ltd/starling-payments-objects#11]
Fetching transactions from an account now include `additionalRemittanceInformation`. This is also available in the FPS scheme webhooks.

**Comment by judgej** [comment]
The API simulator does not support adding a `additionalRemittanceInformation`. The sandbox accounts also do not list a `additionalRemittanceInformation` in the webhooks nor in the `PaymentDetails` model. This can make testing against the sandbox a little tricky, since we cannot see a `additionalRemittanceInformation` value - even an empty field - anywhere in the sandbox.

**Comment by bradydan** [comment]
This means we are 'flying blind' during development. We can only see the `additionalRemittanceInformation` field in production. Not ideal. Starling need to update their sandbox to match production.

**Comment by judgej** [comment]
Fixed with release 1.1.1
